baseURL = 'http://first-hugo.s3-website.us-east-2.amazonaws.com'
languageCode = 'en-us'
title = 'Helloes World'
theme = "ananke"

[[deployment.targets]]
# An arbitrary name for this target.
name = "awsbucket"
URL = "s3://first-hugo/?region=us-east-2" #your bucket here